# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkAct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='locale',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='interest',
            name='content',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='theme',
            name='content',
            field=models.CharField(default='', max_length=100),
        ),
    ]
