# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 11:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkAct', '0002_auto_20160726_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
