# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkAct', '0002_auto_20160725_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='introduction',
            field=models.CharField(default='[]', max_length=500),
        ),
    ]
