# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkAct', '0003_auto_20160725_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='waiting_deal_friends',
            field=models.CharField(default='[]', max_length=300),
        ),
    ]
