# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkAct', '0003_auto_20160726_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
