# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LinkAct', '0007_comment_comment_time'),
        ('LinkAct', '0005_activity_act_image'),
    ]

    operations = [
    ]
