# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkAct', '0008_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='linked_theme',
            field=models.CharField(default='[]', max_length=500),
        ),
    ]
